### ISSUE TITLE
无法获取到自定义的function

### ISSUE THREAD

**Issue by q88888888q** [leancloud/slim-getting-started#1]
操作系统：win10
PHP 5.5.30 (cli) (built: Sep 30 2015 13:50:53)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

[Mon Nov 28 11:11:11 2016] 127.0.0.1:50161 [404]: /1.1/functions/_ops/metadatas - No such file or directory
[Mon Nov 28 11:11:11 2016] 127.0.0.1:50162 [404]: /1.1/functions/_ops/metadatas - No such file or directory
get functions error:  invalid character '<' looking for beginning of value
get functions error:  invalid character '<' looking for beginning of value
[Mon Nov 28 11:11:17 2016] 127.0.0.1:50172 [404]: /1.1/functions/_ops/metadatas - No such file or directory
get functions error:  invalid character '<' looking for beginning of value

**Comment by juvenn** [comment]
请提供一下你的 PHP 版本号，以及运行环境，比如是 WAMP 3.0.6，或者是其它第三方分发版本？
